### PR TITLE
Lab 2 with changes to Lab 1

### PR DESCRIPTION
**Pull request by jnelson7**
I have recently completed another exercise walking users through the functionality of the Streamflow Stats tool.  It made sense to me to separate Lab 1 and Lab 2 due to the time it takes to run through the exercises.  The images have not yet been changed as you have requested.  I am still working on a solution for that.  Please let me know of any feedback you have regarding any aspect of Lab 1 or Lab 2.  Also, please let me know if the captions under the images are showing up on your side.  For some reason they show up when I knit on my desktop computer but do not show up on my laptop.

Thank you.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Big 👍 on this! I'll merge and review. Maybe I can figure out the image thing.

**Comment by jnelson7** [comment]
I merged and pulled the changes down.  Unfortunately I am not able to knit the first two labs because the program doesn't seem to recognize the location of the images.  I'm currently trying to figure this out but if you have any suggestions I'd be happy to try them!

Thanks.

**Comment by dblodgett-usgs** [comment]
If you do 'system.file("Lab1_NWC-DP_Images/Figure1.jpg", package = "NWCEd")' in the main terminal, do you get a path to that file?

**Comment by jnelson7** [comment]
Yes.  The file path is referencing a location on my local C drive.  The
location, however, is different from the location of the saved project.  Is
there a specific location it should be referencing?

On Wed, Jun 8, 2016 at 12:14 PM, David Blodgett notifications@github.com
wrote:

> If you do 'system.file("Lab1_NWC-DP_Images/Figure1.jpg", package =
> "NWCEd")' in the main terminal, do you get a path to that file?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224680255,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw1CtI5VM-3IKIohI6QhZe3T2rzQsks5qJwaCgaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
Yes. It should be where the package is installed. The file is not at the path that the command returns?

**Comment by jnelson7** [comment]
Putting 'system.file("Lab1_NWC-DP_Images/Figure1.jpg", package = "NWCEd")'
into the console returns the file
path "C:/Users/jaken/OneDrive/Documents/R/win-library/3.2/NWCEd/Lab1_NWC-DP_Images/Figure1.jpg".
The file path for the location of the project on my laptop is
"C:\Research\RStudioProject\NWCEd".  When following the file path for the
project on my laptop, I am able to access all the files and folders,
including the ones that were changed ("Lab1_NWC-DP_Images").

Is the '/R/win-library/3.2/NWCEd' supposed to be in the same location as my
saved project?

On Wed, Jun 8, 2016 at 6:09 PM, David Blodgett notifications@github.com
wrote:

> Yes. It should be where the package is installed. The file is not at the
> path that the command returns?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224768064,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw23t_Cjhkjk4PgTX-7VEIB152kyEks5qJ1mpgaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
No, the R/win-library is where the package gets installed. The file should get put there when the you build and reload. Is it not there?

**Comment by jnelson7** [comment]
There is an NWCEd folder under the R/win-library file path.  However, there
is no Rstudio project with the associated "inst" and "man" folders.

On Thu, Jun 9, 2016 at 9:45 AM, David Blodgett notifications@github.com
wrote:

> No, the R/win-library is where the package gets installed. The file should
> get put there when the you build and reload. Is it not there?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224937014,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw12y_TcnqIn3c-VCruCSE31ihklYks5qKDUBgaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by ldecicco-USGS** [comment]
I haven't pinpointed the issue, but what has happened to me in the past is that Build and Reload is not enough if I depend on something that I am accessing by getting the system.file path. I need to actually Build Source Package (it's another option in the Build tab under More).  From the message spit out on the Build Source, I can install from source:

```
#This is from the "Build Source Package"
devtools::build()

"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build "D:\LADData\RCode\dataRetrieval"  \
  --no-resave-data --no-manual 

* checking for file 'D:\LADData\RCode\dataRetrieval/DESCRIPTION' ... OK
* preparing 'dataRetrieval':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'dataRetrieval_2.5.8.tar.gz'

[1] "D:/LADData/RCode/dataRetrieval_2.5.8.tar.gz"

#Then I do this:
install.packages("D:/LADData/RCode/dataRetrieval_2.5.8.tar.gz", repos = NULL, type="source")
```

**Comment by jnelson7** [comment]
Thank you.  Unfortunately I'm not quite understanding what the end result
should look like after performing those steps.  I followed the example and
did not see any change occur.

In my project folder, I have the following items:
[image: Inline image 1]

In the R folder, there are 6 files which I believe are for the functions
which have been created for the project.

When I follow the R/win-library file path, I am able to see the following:
[image: Inline image 2]
The R folder in this location only has 3 files:

[image: Inline image 3]

I'm not sure what the difference is between these file paths/directories.
I noticed as well that the R/win-library path was automatically saved under
my OneDrive.  I'm wondering if it should be saved instead in my C drive.

On Thu, Jun 9, 2016 at 9:52 AM, Laura DeCicco notifications@github.com
wrote:

> I haven't pinpointed the issue, but what has happened to me in the past is
> that Build and Reload is not enough if I depend on something that I am
> accessing by getting the system.file path. I need to actually Build Source
> Package (it's another option in the Build tab under More). From the message
> spit out on the Build Source, I can install from source:
> 
> #This is from the "Build Source Package"
> devtools::build()
> 
> "C:/PROGRA~1/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
>   --no-restore --quiet CMD build "D:\LADData\RCode\dataRetrieval"  \
>   --no-resave-data --no-manual
> - checking for file 'D:\LADData\RCode\dataRetrieval/DESCRIPTION' ... OK
> - preparing 'dataRetrieval':
> - checking DESCRIPTION meta-information ... OK
> - installing the package to build vignettes
> - creating vignettes ... OK
> - checking for LF line-endings in source and make files
> - checking for empty or unneeded directories
> - looking to see if a 'data/datalist' file should be added
> - building 'dataRetrieval_2.5.8.tar.gz'
> 
> [1] "D:/LADData/RCode/dataRetrieval_2.5.8.tar.gz"
> 
> #Then I do this:
> install.packages("D:/LADData/RCode/dataRetrieval_2.5.8.tar.gz", repos = NULL, type="source")
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224939224,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw66r6yLGnsmfY2XG302wknF1Jh0oks5qKDa3gaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by ldecicco-USGS** [comment]
OK, I'm looking at what you guys are doing finally. This is just to get the images in? You don't need full paths, you can use relative ones. 

So instead of:

```
![**Figure 1: The NWC-DP homepage.**]( `r I(system.file("Lab1_NWC-DP_Images/Figure1.jpg", package = "NWCEd"))` )
```

Try:

```
![**Figure 1: The NWC-DP homepage.**]( Lab1_NWC-DP_Images/Figure1.jpg )
```

**Comment by jnelson7** [comment]
That seems to be working.  The error message is passing over Figure1 and
moving to Figure2.  I make the changes and let you know if I run into any
other problems.

Thank you so much!

On Thu, Jun 9, 2016 at 10:17 AM, Laura DeCicco notifications@github.com
wrote:

> OK, I'm looking at what you guys are doing finally. This is just to get
> the images in? You don't need full paths, you can use relative ones.
> 
> So instead of:
> 
> **Figure 1: The NWC-DP homepage.**)` )
> 
> Try:
> 
> **Figure 1: The NWC-DP homepage.**
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224946788,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw_jcELuN2XYsa1ehU1oKuOsSFmx3ks5qKDyigaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by ldecicco-USGS** [comment]
Also, just FYI, if you want to do vignettes "right", you should put the markdown files in a "vignette" folder, then use `devtools` to build the vignettes, which will create and move all the files to inst/doc...then you'd want to add to the DESCRIPTION file:

```
VignetteBuilder: knitr
BuildVignettes: true
```

unsolicited advice, no need to actually do unless you want to submit to CRAN someday

**Comment by jnelson7** [comment]
Thanks!  I think that's the direction we are heading.

On Thu, Jun 9, 2016 at 10:25 AM, Laura DeCicco notifications@github.com
wrote:

> Also, just FYI, if you want to do vignettes "right", you should put the
> markdown files in a "vignette" folder, then use devtools to build the
> vignettes, which will create and move all the files to inst/doc...then
> you'd want to add to the DESCRIPTION file:
> 
> VignetteBuilder: knitr
> BuildVignettes: true
> 
> unsolicited advice, no need to actually do unless you want to submit to
> CRAN someday
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224948955,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw4S-OmEpot3yInaTCUoCP1NkZ9Hgks5qKD5vgaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
@jnelson7 - remember that we need these to work whether the user has the source or if they've just installed the package. The reason we were trying to use the system.file call was so the images got installed with the package and could be used in an ad-hoc markdown report (one of the labs). 

I think you should sort out how to install the package so the images end up in the right place and the system.path pattern works.

**Comment by ldecicco-USGS** [comment]
OK, @dblodgett-usgs explained why these aren't traditional vignettes, and why he's interested in using full paths. Unfortunately, I think that's a pandoc problem:

https://github.com/rstudio/rmarkdown/issues/238

I tried a couple of alternatives, and nothing works seamlessly in markdown. What you could do is include a function which saves the images from the system.file path to the working directory.

**Comment by jnelson7** [comment]
Ok.  I will try doing that.  Thank you for the suggestion.

On Thu, Jun 9, 2016 at 11:57 AM, Laura DeCicco notifications@github.com
wrote:

> OK, @dblodgett-usgs https://github.com/dblodgett-usgs explained why
> these aren't traditional vignettes, and why he's interested in using full
> paths. Unfortunately, I think that's a pandoc problem:
> 
> rstudio/rmarkdown#238 https://github.com/rstudio/rmarkdown/issues/238
> 
> I tried a couple of alternatives, and nothing works seamlessly in
> markdown. What you could do is include a function which saves the images
> from the system.file path to the working directory.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224976000,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtwxJ796IQak1_g5wkrC6xxoEfjgTRks5qKFQcgaJpZM4Iai3W
> .

## 

Jake Nelson

**Comment by jnelson7** [comment]
Laura,

There are some things I'm still not quite understanding.  The images are
saved in both locations on my computer, both where the project is saved and
in the R/win-library/ location. I'm not quite sure what you are meaning by
saving the images from the system.file path to the working directory.  Any
clarification on this would be great.

Thank you.

On Thu, Jun 9, 2016 at 12:40 PM, Jake Nelson jake.nelson7@gmail.com wrote:

> Ok.  I will try doing that.  Thank you for the suggestion.
> 
> On Thu, Jun 9, 2016 at 11:57 AM, Laura DeCicco notifications@github.com
> wrote:
> 
> > OK, @dblodgett-usgs https://github.com/dblodgett-usgs explained why
> > these aren't traditional vignettes, and why he's interested in using full
> > paths. Unfortunately, I think that's a pandoc problem:
> > 
> > rstudio/rmarkdown#238 https://github.com/rstudio/rmarkdown/issues/238
> > 
> > I tried a couple of alternatives, and nothing works seamlessly in
> > markdown. What you could do is include a function which saves the images
> > from the system.file path to the working directory.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224976000,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ARBtwxJ796IQak1_g5wkrC6xxoEfjgTRks5qKFQcgaJpZM4Iai3W
> > .
> 
> ## 
> 
> Jake Nelson

## 

Jake Nelson

**Comment by ldecicco-USGS** [comment]
As far as I can tell, and I've run into this before, in Windows rmarkdown cannot handle images that use full paths (so the path has to be relative to where the .Rmd file is). So, if your user is on a Windows computer, you'll need to somehow get those images to get saved to their working directory (or, really, where-ever the .Rmd files will be). 

There are probably lots of ways this could be done (write a function and just instruct the user to run the function, have it copy the files on install)...most importantly, make sure you give clear instructions to the user)...

**Comment by dblodgett-usgs** [comment]
I think we should just switch back to the way we had it with the images at URLs on github. I wasn't aware of the windows complication. Sorry for all the run around!!

**Comment by jnelson7** [comment]
An update on the image issue:

The last few days I searched for answers to the issue regarding the images
as mentioned previously.  After having a few graduate students in the lab
as well as a faculty member take a look at the issue, a solution has not
yet been determined.  Thus far the problem is believed to stem from a file
path problem associated with running RStudio on Windows.

Attached is a text file with the code and associated error statement.  Any
suggestions on how to fix this would be greatly appreciated.

Thank you.

On Thu, Jun 9, 2016 at 12:54 PM, Jake Nelson jake.nelson7@gmail.com wrote:

> Laura,
> 
> There are some things I'm still not quite understanding.  The images are
> saved in both locations on my computer, both where the project is saved and
> in the R/win-library/ location. I'm not quite sure what you are meaning by
> saving the images from the system.file path to the working directory.  Any
> clarification on this would be great.
> 
> Thank you.
> 
> On Thu, Jun 9, 2016 at 12:40 PM, Jake Nelson jake.nelson7@gmail.com
> wrote:
> 
> > Ok.  I will try doing that.  Thank you for the suggestion.
> > 
> > On Thu, Jun 9, 2016 at 11:57 AM, Laura DeCicco notifications@github.com
> > wrote:
> > 
> > > OK, @dblodgett-usgs https://github.com/dblodgett-usgs explained why
> > > these aren't traditional vignettes, and why he's interested in using full
> > > paths. Unfortunately, I think that's a pandoc problem:
> > > 
> > > rstudio/rmarkdown#238 https://github.com/rstudio/rmarkdown/issues/238
> > > 
> > > I tried a couple of alternatives, and nothing works seamlessly in
> > > markdown. What you could do is include a function which saves the images
> > > from the system.file path to the working directory.
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/dblodgett-usgs/NWCEd/pull/7#issuecomment-224976000,
> > > or mute the thread
> > > https://github.com/notifications/unsubscribe/ARBtwxJ796IQak1_g5wkrC6xxoEfjgTRks5qKFQcgaJpZM4Iai3W
> > > .
> > 
> > ## 
> > 
> > Jake Nelson
> 
> ## 
> 
> Jake Nelson

## 

Jake Nelson

# The code responsible for finding and displaying the image from the identified path.

**Figure 1: The NWC-DP homepage.**)` )

# The error received after trying to Knit to HTML

processing file: Lab_1.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |.................................................................| 100%
   inline R code fragments

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Lab_1.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Lab_1.html --smart --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --template "C:\Users\Jake\Documents\R\win-library\3.2\rmarkdown\rmd\h\default.html" --number-sections --variable "theme:cerulean" --include-in-header "C:\Users\Jake\AppData\Local\Temp\Rtmpc9E3AB\rmarkdown-str32c81397acb.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --highlight-style tango --variable "navigationjs=C:\Users\Jake\Documents\R\win-library\3.2\rmarkdown\rmd\h\navigation-1.0" 
output file: Lab_1.knit.md

pandoc.exe: Could not fetch C:/Users/Jake/Documents/R/win-library/3.2/NWCEd/Lab1_NWC-DP_Images/Figure1.jpg
InvalidUrlException "C:/Users/Jake/Documents/R/win-library/3.2/NWCEd/Lab1_NWC-DP_Images/Figure1.jpg" "Invalid scheme"
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Lab_1.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Lab_1.html --smart --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --template "C:\Users\Jake\Documents\R\win-library\3.2\rmarkdown\rmd\h\default.html" --number-sections --variable "theme:cerulean" --include-in-header "C:\Users\Jake\AppData\Local\Temp\Rtmpc9E3AB\rmarkdown-str32c81397acb.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --highlight-style tango --variable "navigationjs=C:\Users\Jake\Documents\R\win-library\3.2\rmarkdown\rmd\h\navigation-1.0"' had status 67 
Execution halted

**Comment by dblodgett-usgs** [comment]
We should switch back to referencing them by url as you had before to allow us to move forward. This approach is too problematic.

**Pull request merged**
