### PR TITLE
Changes to Labs 1-4

### PR DESCRIPTION
**Pull request by jnelson7**
I've included a "Try It Yourself" section for Labs 1-3 and created Lab 4.  Lab 4 still needs a "Try It Yourself" section.  Buttons have been created to show/hide code for each of the graphs.  If approved, I can add it to Lab 4.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@jnelson7 - these are looking great! I'll need to look more closely at things when I have a few minutes this week. Go ahead and work in some exercises for lab 4.

Can you see if we could distribute this through: https://github.com/cuahsi ? I think it would be better if it were in the CUAHSI space rather than USGS.

**Comment by jnelson7** [comment]
Thank you.

I will look into the CUAHSI component today.

On Mon, Jul 4, 2016 at 1:20 PM, David Blodgett notifications@github.com
wrote:

> @jnelson7 https://github.com/jnelson7 - these are looking great! I'll
> need to look more closely at things when I have a few minutes this week. Go
> ahead and work in some exercises for lab 4.
> 
> Can you see if we could distribute this through: https://github.com/cuahsi
> ? I think it would be better if it were in the CUAHSI space rather than
> USGS.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/10#issuecomment-230344341,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw545ZBHWAafEXDsAt-AJNidnRPNMks5qSV0QgaJpZM4JDuQM
> .

## 

Jake Nelson

**Comment by jnelson7** [comment]
I just received word from Dr. Ames that he will ask about the distribution
at a CUAHSI meeting he will be attending later this month.  Until then,
will we just keep the material at https://github.com/dblodgett-usgs/NWCEd ?

On Tue, Jul 5, 2016 at 10:17 AM, Jake Nelson jake.nelson7@gmail.com wrote:

> Thank you.
> 
> I will look into the CUAHSI component today.
> 
> On Mon, Jul 4, 2016 at 1:20 PM, David Blodgett notifications@github.com
> wrote:
> 
> > @jnelson7 https://github.com/jnelson7 - these are looking great! I'll
> > need to look more closely at things when I have a few minutes this week. Go
> > ahead and work in some exercises for lab 4.
> > 
> > Can you see if we could distribute this through:
> > https://github.com/cuahsi ? I think it would be better if it were in the
> > CUAHSI space rather than USGS.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/dblodgett-usgs/NWCEd/pull/10#issuecomment-230344341,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ARBtw545ZBHWAafEXDsAt-AJNidnRPNMks5qSV0QgaJpZM4JDuQM
> > .
> 
> ## 
> 
> Jake Nelson

## 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
Sounds good.

**Pull request merged**
