### PR TITLE
Lab 3 changes with 2 box plots

### PR DESCRIPTION
**Pull request by jnelson7**
I have added a folder for images under the inst folder.  Images are referenced on my desktop.  As soon as they are merged into the correct location I can update the image referencing. There are 2 box plots which have been created.  Lab 3 is not complete yet.  More changes will follow soon.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
👍  Let me know when you are ready for me to review...

**Comment by jnelson7** [comment]
I just met with Dan and am incorporating his suggested changes.  It should
be ready for review by later this afternoon.

Thank you.

On Wed, Jun 22, 2016 at 2:32 AM, David Blodgett notifications@github.com
wrote:

> 👍 Let me know when you are ready for me to review...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dblodgett-usgs/NWCEd/pull/9#issuecomment-227677936,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARBtw1aDUvk-EstRi0YMsfaovWQ4M6pnks5qOPM1gaJpZM4I6ODa
> .

## 

Jake Nelson

**Comment by jnelson7** [comment]
Mr. Blodgett,

Lab 3 is ready to be reviewed.  If I did the pull request correctly, the
bottom of the lab should have a section titled "Do It Yourself".  I thought
that this future section could have material about communicating with
stakeholders, but I am happy to change it however you'd like.  Please let
me know if this is not the version you are able to see.

Thank you.

On Wed, Jun 22, 2016 at 11:59 AM, Jake Nelson jake.nelson7@gmail.com
wrote:

> I just met with Dan and am incorporating his suggested changes.  It should
> be ready for review by later this afternoon.
> 
> Thank you.
> 
> On Wed, Jun 22, 2016 at 2:32 AM, David Blodgett notifications@github.com
> wrote:
> 
> > 👍 Let me know when you are ready for me to review...
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/dblodgett-usgs/NWCEd/pull/9#issuecomment-227677936,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ARBtw1aDUvk-EstRi0YMsfaovWQ4M6pnks5qOPM1gaJpZM4I6ODa
> > .
> 
> ## 
> 
> Jake Nelson

## 

Jake Nelson

**Comment by dblodgett-usgs** [comment]
This looks great, Jake! 

For the histograms, it might be interesting to look at monthly ET or daily Precip. Maybe not, just something to consider. Let's get the full suite of labs drafted then revisit the content as a whole in a review capacity.

**Pull request merged**
